feat: 임시 비밀번호 발급 및 이메일로 전송하는 기능 작성
geezers-io/frolic-backend pull request #37
Opened 2023-01-22 08:47 UTC by Rungky

## Type
- [x] Feature
- [ ] Fix

**Jira Tickets** 
[issue #FL-116]https://geezers.atlassian.net/browse/FL-116
[issue #FL-117]https://geezers.atlassian.net/browse/FL-117
[issue #FL-118]https://geezers.atlassian.net/browse/FL-118
[issue #FL-119]https://geezers.atlassian.net/browse/FL-119

## What & Why
임시 비밀번호 발급 기능 작성 및 이메일 전송 기능을 작성하였습니다.

## Test Result

2023-01-22 11:46 UTC, galaxy4276 requested changes
테스트 코드는 작성 중인 것으로 파악되어 따로 리뷰 진행하지 않았습니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
> +  @PostMapping("/tempPassword")
[변경 요청]
엔드포인트 형식 문서 재참고 바랍니다.
![image](https://user-images.githubusercontent.com/50310464/213913377-fcd0ace1-91e8-4cb6-add1-15585cf6e571.png)

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
> +    System.out.println("verifyCodeRequest : " + verifyCodeRequest);
[변경 요청]
개발 테스트를 위한 로그 코드는 제거해주세요.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
> +  @PostMapping("/tempPassword/check")
엔드포인트 형식 문서 재참고

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/api/UserInfoFinderApi.java
> +    sendTempPasswordManager.changeTempPassword(email, phoneNumber, password);
컨트롤러와 서비스에 대한 로직 분리 수행해주시면 더 좋은 코드가 될 것 같습니다.
(REST Api 에서 Controller 는 Http 요청에 대한 처리를 관여, 서비스는 비즈니스 로직을 처리함 )

### 참고
[[Spring] MVC Layering Architecture : Controller와 Service의 책임 나누기](https://umbum.dev/1066)

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    String userEmail = userRepository.getUserInfoPwExist(request.getEmail(), request.getPhoneNumber()).toString();
[질문]
실제로 사용하지 않은 구문인 것으로 확인되었는데, 사용 의도가 궁금합니다.
메서드 이름 의미 또한 실제로 수행하는 처리에 적합하지 않은 것으로 보입니다.

> `getUser..` 이나 실제로 `email(String)` 값을 가져옴

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    //send(request.getPhoneNumber(), FinderConstants.PASSWORD_AUTHCODE_SEND_MESSAGE + code);
[변경 요청]
핵심 코드가 주석 처리 된 것으로 보임

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    return userInfoExist;
[의견]
* 필요 없는 return 값이 발생하고 있음.
* 이메일 찾기 기능과 중복되는 코드가 많음.

이 부분은 제가 다음 PR 때 수정해보도록 하겠습니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +  public String phoneNumberVal(String email){
[의견]
메서드는 특정한 행위를 의미하기 때문에 동사로 시작되게 끔 변경하는게 좋은 것 같습니다.
제가 작성한 `authCodeVerifty` 또한 잘못된 명명 규칙이니 다음 PR 때 수정하도록 하겠습니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    javaMailSender.send(message);
[의견]
메일을 전송하는 부분만 따로 서비스 객체를 설계 및 작성하여 사용하면 의존성 분리 및 더 클린한 코드가 유지될 것 같다는 생각이 들었습니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    userRepository.setTempPassword(encodedPassword, email, phoneNumber);
[의견]
JPA 에서 기본으로 update 메서드를 제공하지 않은 이유는 모든 엔티티 객체에 대해 영속성 컨텍스트로 관리하기 때문입니다.
해당 부분은 JPA의 특성을 고려하여 적절하게 사용하도록 변경하면 더 좋은 코드가 될 것 같습니다.

[[Spring JPA] 영속성 컨텍스트(Persistence Context)](https://velog.io/@seongwon97/Spring-Boot-%EC%98%81%EC%86%8D%EC%84%B1-%EC%BB%A8%ED%85%8D%EC%8A%A4%ED%8A%B8Persistence-Context)

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/user/repository/UserRepository.java
> +  @Transactional
[변경 요청]
repository 코드에 트랜잭션 코드는 안넣어줘도 서비스 레이어에서 적용됩니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/user/repository/UserRepository.java
> +  void setTempPassword(@Param("password") String password,
[의견]
기존 정보를 바꾸는 행위에 대해 `set` 보단 `change`가 더 와닿는 것 같습니다.

2023-01-22 11:46 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/user/repository/UserRepository.java
> +  Optional<String> getPhoneNumberByEmail(@Param("email") String email);
[변경 요청]
해당 코드는 `Controller Layer` 에서 기존에 요청했던 사용자에 대한 정보를 가져오기 위해 사용되는 것으로 파악되었는데,
Cache DB 에 `AuthCode` 객체로 해당 정보를 사전에 보관하고 있기 떄문에 `Cookie` 에서 가져오는 `id` 로 식별하여 사용하는 것이 성능 개선 과 로직 분산을 줄이기 목적으로 더 적합한 것 같습니다.

2023-01-23 15:16 UTC, Rungky commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +    String userEmail = userRepository.getUserInfoPwExist(request.getEmail(), request.getPhoneNumber()).toString();
아 그러네요,,! 잘못 작성한거 같습니다 . 해당 코드는 삭제하도록 하겠습니다.

2023-02-08 14:52 UTC, Rungky commented on src/main/java/com/frolic/sns/auth/dto/UserTempPasswordRequest.java
> +  }
이 부분으로 데이터가 가도록 하려고 했는데 실행하면 model안에 있는 User로 이동합니다.

2023-02-08 14:55 UTC, Rungky commented on src/main/java/com/frolic/sns/auth/application/finder/SendTempPasswordManager.java
> +  }
이 부분도 값들은 로그에 출력 되지만 model에 user로 이동합니다.

2023-02-08 14:58 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/auth/dto/UserTempPasswordRequest.java
> +  }
유저의 패스워드를 변경하는 것이니 model 의 User 로 반환되는 것이 정상입니다.

db 내의 유저테이블과 User 엔티티 모델 간 관계에 대해 알아보면 프로세스 흐름을 파악하기 수월할 것 같습니다

2023-02-19 08:10 UTC, galaxy4276 approved these changes
해당 기능 작업 하시느라 고생하셨습니다

2023-02-19 08:21 UTC, merged