Feat/fl 145
geezers-io/frolic-backend pull request #50
Opened 2023-03-07 15:32 UTC by Rungky

## Type
- [ X ] Feature
- [ ] Fix

**Jira Tickets** 
https://geezers.atlassian.net/browse/FL-145

## What & Why
전체 게시물을 조회해오는 기능입니다. (아직 작성중)
UnsatisfiedDependencyException 에러 발생중

## Test Result

2023-03-07 16:07 UTC, galaxy4276 requested changes
리뷰 견적 드립니다.

2023-03-07 16:07 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/post/application/v2/SelectPostBusinessManager.java
> +                .collect(Collectors.toList());
[요청]
반환 되는 값은 List 자료형인데, PostInfo 단일 객체로 수동 형 변환 되면 런타임 단계에서 에러가 발생할 것 같아요.
PsotInfo 의 Builder 패턴을 활용하여 객체 초기화를 수행하는 방법은 어떨까요?

2023-03-07 16:32 UTC, Rungky commented on src/main/java/com/frolic/sns/post/application/v2/CreatePostBusinessManager.java
> +      .addCommentCount(Long.valueOf(0))
[https://geezers.atlassian.net/browse/FL-145]
게시글에 달린 댓글의 총 갯수를 내려주는 것 입니다! 댓글 총 갯수에 관한 부분은 
위 링크에 설명부분에 작성되어 있어 변경했습니다! 

[의견]
게시글 생성 시에 댓글 카운트를 내려주는 것은 적합하지 않은가요? 저도 지금 보다보니 헷갈리네요..!

2023-03-07 18:54 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/post/application/v2/CreatePostBusinessManager.java
> +      .addCommentCount(Long.valueOf(0))
제가 혼란을 드렸네요. 
진행하고 계신 내용이 맞는 것 같아요.

2023-03-07 18:55 UTC, galaxy4276 commented
브랜치는 항상 main 기준으로 생성해주세요!
이전 브랜치에 있는 커밋 내용이 포함되면 불필요한 기록도 내포하게 됩니다.

2023-03-12 09:06 UTC, bear-bear-bear commented on src/main/java/com/frolic/sns/post/application/PostCrudManagerImpl.java
> +}
[질문]

의도된 주석인가요?

2023-03-12 09:06 UTC, bear-bear-bear commented on src/main/java/com/frolic/sns/post/application/PostFileManagerImpl.java
> +//    fileService.uploadMultipleFile(files);
[질문]

의도된 주석인가요?

2023-03-12 09:06 UTC, bear-bear-bear commented on src/main/java/com/frolic/sns/post/application/v2/GetPostBusinessManager.java
> +    //List<FileInfo> files = postFileRepository.getFilesByPostId(post.getId());
[질문]

의도된 주석인가요?

2023-03-12 09:06 UTC, bear-bear-bear commented on src/main/java/com/frolic/sns/post/dto/CreateCommentRequest.java
>  //  @Max(value = 500, message = "본문 데이터는 500자 이하여야 합니다.")
[질문]

의도된 주석인가요?

2023-03-12 09:06 UTC, bear-bear-bear commented on src/main/java/com/frolic/sns/post/repository/PostFileRepository.java
> +    //List<FileInfo> getFilesByPostId(Long postId);
[질문]

의도된 주석인가요?

2023-03-12 09:09 UTC, Rungky commented on src/main/java/com/frolic/sns/post/repository/PostFileRepository.java
> +    //List<FileInfo> getFilesByPostId(Long postId);
이부분은 전에 에러 나서 주석처리 했던건데 수정을 안했네요. 바로 고쳐서 올리겠습니다!

2023-03-12 09:12 UTC, Rungky commented on src/main/java/com/frolic/sns/post/application/v2/GetPostBusinessManager.java
> +    //List<FileInfo> files = postFileRepository.getFilesByPostId(post.getId());
이부분도 사용하지 않는 코드네요! 지우겠습니다!

2023-03-12 09:50 UTC, Rungky commented on src/main/java/com/frolic/sns/post/dto/CreateCommentRequest.java
>  //  @Max(value = 500, message = "본문 데이터는 500자 이하여야 합니다.")
삭제했던 코드인데 제pr과 병합하면서 살아났다고 하네요 제거하겠습니다!

2023-03-12 09:50 UTC, Rungky commented on src/main/java/com/frolic/sns/post/application/PostFileManagerImpl.java
> +//    fileService.uploadMultipleFile(files);
삭제했던 코드인데 제pr과 병합하면서 살아났다고 하네요 제거하겠습니다!

2023-03-12 09:51 UTC, Rungky commented on src/main/java/com/frolic/sns/post/application/PostCrudManagerImpl.java
> +}
삭제했던 코드인데 제pr과 병합하면서 살아났다고 하네요 제거하겠습니다!

2023-03-12 12:00 UTC, jeidiiy commented on src/main/java/com/frolic/sns/post/repository/LikeDslRepository.java
> +public class LikeDslRepository {
이건 어떤 용도인가요?

2023-03-12 12:06 UTC, jeidiiy commented on src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
>    @PostMapping()
CommentCrudApi의 createCommentApi 에서는 @PostMapping("")을 사용했는데 여기선 @PostMapping()로 작성하셨네요. 혹시 차이가 있을까요?

2023-03-12 12:11 UTC, jeidiiy submitted a review, later dismissed
전체적으로 잘 개발하신 것으로 보입니다. 이것이 이 팀의 백엔드 수준인가요? 범접할 수 없군요.

2023-03-12 12:26 UTC, Rungky commented on src/main/java/com/frolic/sns/post/repository/LikeDslRepository.java
> +public class LikeDslRepository {
user의 좋아요 여부를 QueryDsl로 작성하기 위해 만들었던 클래스인데 likeRepository에 existsByPostAndUser가 있어 현재는 사용하지 않는 클래스 입니다!

2023-03-12 12:33 UTC, Rungky commented on src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
>    @PostMapping()
제가 작성한 부분은 아닌데 궁금하네요! 차이가 있나요..?

2023-03-12 12:46 UTC, jeidiiy commented on src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
>    @PostMapping()
공식 문서를 보면 차이가 없습니다. 사용할 거면 하나의 방법으로 통일하는 편이 좋아 보입니다.
@PostMapping == @PostMapping("") == @PostMapping()
![image](https://user-images.githubusercontent.com/57584529/224545513-d196d291-d153-478c-bbae-40637ea12d9a.png)

2023-03-13 00:36 UTC, jeidiiy approved these changes

2023-03-13 00:55 UTC, galaxy4276 approved these changes
피드백에 대한 수정 중 누락되거나 잘못 제거된 내용 수정 및 복구했어요!
이전 버전의 api 관련하여 더 이상 사용되지 않은 객체는 제거처리하였습니다 😁

2023-03-13 00:55 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/post/api/PostCrudV2Api.java
>    @PostMapping()
@PostMapping 으로 사용가능한 부분은 처음 알았네요.
정보 주셔서 감사합니다.

2023-03-13 00:55 UTC, galaxy4276 commented on src/main/java/com/frolic/sns/post/repository/PostDslRespository.java
> +  }
[의견]
@Rungky 이 부분 사용 예정인 지 확인 부탁드릴게요.

2023-03-13 10:50 UTC, galaxy4276 approved these changes
긴 여정 수고하셨습니다

2023-03-13 10:53 UTC, merged